BSP-9173 start psplash earlier in boot sequence

diff --git a/files/configos/etc/init.d/rcS b/files/configos/etc/init.d/rcS
--- a/files/configos/etc/init.d/rcS
+++ b/files/configos/etc/init.d/rcS
@@ -23,24 +23,44 @@ ETCTMPMNT=/mnt/etcfs/
 FACTORYPARTITION=/dev/mmcblk1p1
 FACTORYTMPMNT=/mnt/factory/
 
-#	Make sure proc is mounted
-#
-[ -d "/proc/1" ] || mount /proc
+# Mount system fs
+mount -t proc proc /proc
+mount -t sysfs sysfs /sys
 
-#
-#	Source defaults.
-#
+# Source defaults.
 . /etc/default/rcS
 
-#
-#	Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
-#
+# Trap CTRL-C &c only in this shell so we can interrupt subprocesses.
 trap ":" INT QUIT TSTP
-
-#
-#      Verify mmcblk1p5 is populated (if no, copy /etc to it) and mount it over /etc 
-# 
+ 
 mount -t tmpfs -o rw,size=1M tmpfs /mnt
+
+# Mount factory partition to get the splash image (if mount fails, perform format+mount)
+mkdir $FACTORYTMPMNT
+mount -o ro $FACTORYPARTITION $FACTORYTMPMNT
+if [ $? -ne 0 ]; then
+   mke2fs -T ext3 -L "factory" $FACTORYPARTITION
+   mount -o ro $FACTORYPARTITION $FACTORYTMPMNT
+fi
+
+# Disable console on framebuffer to avoid showing console output and
+# blinking when starting X
+echo 0 > /sys/class/vtconsole/vtcon1/bind
+
+# Clear console framebuffer
+echo -ne "\ec"  > /dev/tty1
+
+# Clear framebuffer
+[ -e /dev/fb0 ] && cat /dev/zero > /dev/fb0
+
+# Start splash
+export TMPDIR=/mnt/.psplash
+mkdir $TMPDIR
+mount -t tmpfs -o rw,size=40k tmpfs $TMPDIR
+/usr/bin/psplash &
+
+psplash-write "PROGRESS 0"
+
 mkdir $ETCTMPMNT
 
 # creates a temporary rambased etcfs
@@ -51,22 +71,14 @@ cp -a $ETCTMPMNT/* /etc/
 umount $ETCTMPMNT
 rmdir $ETCTMPMNT
 
-# Mount the factory partition (if mount fails, perform format+mount)
-if [ "$ENABLE_ROOTFS_FSCK" = "yes" ]; then
-  fsck -a $FACTORYPARTITION
-fi
-
-mkdir $FACTORYTMPMNT
-mount $FACTORYPARTITION $FACTORYTMPMNT
-
-if [ $? -ne 0 ]; then
-   mke2fs -T ext3 -L "factory" $FACTORYPARTITION 
-   mount $FACTORYPARTITION $FACTORYTMPMNT
-fi
-# creates a link
+# Copy /etc/shadow from etc to the factory partition if not already there
 if [ ! -e $FACTORYTMPMNT'shadow' ] ; then
+  mount -o remount,rw $FACTORYTMPMNT
   cp -a /etc/shadow $FACTORYTMPMNT'shadow'
+  mount -o remount,ro $FACTORYTMPMNT
 fi
+
+# creates a link
 ln -s -b $FACTORYTMPMNT'shadow' /etc/shadow
 chgrp shadow /etc/shadow
 
@@ -81,9 +93,10 @@ mkdir $DATATMPMNT
 mount -o ro $MAINOSPARTITION $MAINOSTMPMNT
 mount $DATAPARTITION $DATATMPMNT
 
-#
-#	Call all parts in order.
-#
+# Update splash progress bar
+PROGRESS_STATE=10
+echo $PROGRESS_STATE > $TMPDIR/progress_state
+psplash-write "PROGRESS $PROGRESS_STATE"
+
+# Call all parts in order
 exec /etc/init.d/rc S
-
-
